
import { useState, useMemo } from 'react';
import { ThumbsUp, ThumbsDown, AlertCircle, Save, Check, Sparkles } from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';

const stuckPointOptions = [
  '费用太贵',
  '担心疼痛',
  '对效果不确定',
  '时间安排问题',
  '想再考虑考虑',
  '不信任方案',
  '和家人商量',
  '其他',
];

const categoryOptions = [
  { value: 'greeting', label: '开场问候' },
  { value: 'medical_history', label: '病史追问' },
  { value: 'pre_exam', label: '检查前说明' },
  { value: 'treatment_explain', label: '方案解释' },
  { value: 'closing', label: '结束语' },
  { value: 'objection_handling', label: '异议处理' },
];

const autoSpeechMap: Record<string, string[]> = {
  '费用太贵': [
    '我理解费用是您比较关心的问题，我们先把方案说清楚，费用这块我们可以分期。',
    '您放心，我们会把每一项费用都列清楚，您可以根据自己的情况选择。',
  ],
  '担心疼痛': [
    '治疗之前我们会打麻药，过程中不会疼的，您放心。',
    '很多患者一开始也担心疼痛，其实现在的技术已经很成熟了，不适感很轻微。',
  ],
  '对效果不确定': [
    '这个方案我们做过很多类似的案例，效果都很不错，您可以看看之前的案例。',
    '我们可以先做一个阶段性方案，您看到效果了再决定后续的。',
  ],
  '时间安排问题': [
    '我们可以根据您的时间来安排就诊，尽量减少您请假的时间。',
    '如果时间不方便，我们可以把治疗分几次做，每次时间短一些。',
  ],
  '想再考虑考虑': [
    '没关系的，这个决定确实需要仔细考虑，您回去想想有什么问题随时联系我们。',
    '我给您一份资料带回去看看，有不清楚的地方随时问我。',
  ],
  '不信任方案': [
    '我给您详细解释一下为什么建议这个方案，您可以看看适不适合您的情况。',
    '如果您有疑虑，我们也可以请主任再帮您看看，给您第二个意见。',
  ],
  '和家人商量': [
    '这个确实需要和家人商量一下，您可以带家人一起来，我们当面沟通更清楚。',
    '好的，您先回去商量，如果有问题可以随时打电话或者再过来看看。',
  ],
};

export function ReviewForm() {
  const [isSmooth, setIsSmooth] = useState<boolean | null>(null);
  const [selectedStuckPoints, setSelectedStuckPoints] = useState<string[]>([]);
  const [customStuckPoint, setCustomStuckPoint] = useState('');
  const [speechContent, setSpeechContent] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('treatment_explain');
  const [saved, setSaved] = useState(false);
  const [showAutoSpeech, setShowAutoSpeech] = useState(false);

  const addReviewRecord = useAppStore((state) => state.addReviewRecord);
  const addPersonalSpeech = useAppStore((state) => state.addPersonalSpeech);

  const toggleStuckPoint = (point: string) => {
    setSelectedStuckPoints((prev) =>
      prev.includes(point) ? prev.filter((p) => p !== point) : [...prev, point]
    );
  };

  const allStuckPoints = useMemo(() => {
    const points = [...selectedStuckPoints];
    if (customStuckPoint.trim() && selectedStuckPoints.includes('其他')) {
      points.push(customStuckPoint.trim());
    }
    return points;
  }, [selectedStuckPoints, customStuckPoint]);

  const autoGeneratedSpeeches = useMemo(() => {
    if (isSmooth === false && allStuckPoints.length > 0) {
      const speeches: { content: string; stuckPoint: string; isCustom: boolean }[] = [];
      allStuckPoints.forEach((point) => {
        const mapped = autoSpeechMap[point];
        if (mapped && mapped.length > 0) {
          speeches.push({ content: mapped[0], stuckPoint: point, isCustom: false });
        } else if (point !== '其他') {
          speeches.push({
            content: `关于"${point}"这个问题，我理解您的顾虑。我们可以详细聊聊，看看怎么能更好地帮您解决。`,
            stuckPoint: point,
            isCustom: true,
          });
        }
      });
      return speeches;
    }
    return [];
  }, [isSmooth, allStuckPoints]);

  const handleSave = () => {
    if (isSmooth === null) return;

    addReviewRecord({
      isSmooth,
      stuckPoint: allStuckPoints.filter((p) => p !== '其他').join('、'),
      speechContent,
    });

    if (speechContent.trim()) {
      addPersonalSpeech({
        content: speechContent.trim(),
        category: selectedCategory,
        tags: [selectedCategory, '手动沉淀'],
      });
    }

    if (isSmooth === false && autoGeneratedSpeeches.length > 0) {
      autoGeneratedSpeeches.forEach((auto) => {
        addPersonalSpeech({
          content: auto.content,
          category: 'objection_handling',
          tags: [
            'objection_handling',
            auto.stuckPoint,
            '自动沉淀',
            auto.isCustom ? '自定义卡点' : '预设卡点',
          ],
        });
      });
    }

    if (isSmooth === true) {
      addPersonalSpeech({
        content: '本次沟通顺利，患者配合度高，话术节奏把握良好，继续保持。',
        category: 'closing',
        tags: ['closing', '顺利复盘', '自动沉淀'],
      });
    }

    setSaved(true);
    setTimeout(() => {
      setSaved(false);
      setIsSmooth(null);
      setSelectedStuckPoints([]);
      setCustomStuckPoint('');
      setSpeechContent('');
      setShowAutoSpeech(false);
    }, 1500);
  };

  return (
    <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
      <h3 className="text-base font-semibold text-gray-800 mb-5 flex items-center gap-2">
        <span className="w-1 h-5 bg-amber-500 rounded-full"></span>
        本次沟通复盘
      </h3>

      <div className="space-y-6">
        <div>
          <label className="text-sm font-medium text-gray-700 mb-3 block">沟通是否顺利？</label>
          <div className="flex gap-3">
            <button
              onClick={() => { setIsSmooth(true); setSelectedStuckPoints([]); }}
              className={`flex-1 flex items-center justify-center gap-2 py-4 rounded-xl border-2 transition-all duration-200 ${
                isSmooth === true
                  ? 'border-emerald-500 bg-emerald-50 text-emerald-600'
                  : 'border-gray-200 text-gray-500 hover:border-gray-300 hover:bg-gray-50'
              }`}
            >
              <ThumbsUp className="w-5 h-5" />
              <span className="font-medium">很顺利</span>
            </button>
            <button
              onClick={() => setIsSmooth(false)}
              className={`flex-1 flex items-center justify-center gap-2 py-4 rounded-xl border-2 transition-all duration-200 ${
                isSmooth === false
                  ? 'border-orange-500 bg-orange-50 text-orange-600'
                  : 'border-gray-200 text-gray-500 hover:border-gray-300 hover:bg-gray-50'
              }`}
            >
              <ThumbsDown className="w-5 h-5" />
              <span className="font-medium">不太顺</span>
            </button>
          </div>
        </div>

        {isSmooth === false && (
          <div className="animate-fade-in">
            <label className="text-sm font-medium text-gray-700 mb-3 block">
              患者主要卡在哪些问题？
            </label>
            <div className="flex flex-wrap gap-2">
              {stuckPointOptions.map((point) => {
                const isSelected = selectedStuckPoints.includes(point);
                return (
                  <button
                    key={point}
                    onClick={() => toggleStuckPoint(point)}
                    className={`px-3 py-1.5 text-sm rounded-lg border transition-all duration-200 ${
                      isSelected
                        ? 'bg-orange-500 text-white border-orange-500'
                        : 'bg-gray-50 text-gray-600 border-gray-200 hover:border-gray-300'
                    }`}
                  >
                    {point}
                  </button>
                );
              })}
            </div>
            {selectedStuckPoints.includes('其他') && (
              <input
                type="text"
                value={customStuckPoint}
                onChange={(e) => setCustomStuckPoint(e.target.value)}
                placeholder="请输入其他卡点问题..."
                className="mt-3 w-full px-4 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500"
              />
            )}
          </div>
        )}

        {isSmooth === false && autoGeneratedSpeeches.length > 0 && (
          <div className="animate-fade-in">
            <div className="flex items-center justify-between mb-2">
              <label className="text-sm font-medium text-gray-700 flex items-center gap-1.5">
                <Sparkles className="w-4 h-4 text-amber-500" />
                系统为您自动生成应对话术
              </label>
              <button
                onClick={() => setShowAutoSpeech(!showAutoSpeech)}
                className="text-xs text-blue-500 hover:text-blue-600"
              >
                {showAutoSpeech ? '收起' : '展开预览'}
              </button>
            </div>
            {showAutoSpeech && (
              <div className="space-y-2 animate-fade-in">
                {autoGeneratedSpeeches.map((auto, idx) => (
                  <div
                    key={idx}
                    className={`p-3 rounded-xl border ${
                      auto.isCustom
                        ? 'bg-blue-50 border-blue-200'
                        : 'bg-amber-50 border-amber-200'
                    }`}
                  >
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <span
                        className={`text-xs px-2 py-0.5 rounded-md ${
                          auto.isCustom
                            ? 'bg-blue-200 text-blue-700'
                            : 'bg-amber-200 text-amber-700'
                        }`}
                      >
                        {auto.stuckPoint}
                      </span>
                      <span
                        className={`text-xs ${
                          auto.isCustom ? 'text-blue-500' : 'text-amber-500'
                        }`}
                      >
                        {auto.isCustom ? '自动沉淀 · 自定义卡点' : '自动沉淀'}
                      </span>
                    </div>
                    <p className="text-sm text-gray-700">{auto.content}</p>
                    {auto.isCustom && (
                      <p className="text-xs text-blue-500 mt-1">
                        这是系统为您生成的通用应对话术，保存后可以在话术库中编辑为您自己的说法
                      </p>
                    )}
                  </div>
                ))}
                <p className="text-xs text-gray-400">
                  保存复盘后，这些话术将自动添加到您的个人话术库，可在库中编辑修改
                </p>
              </div>
            )}
          </div>
        )}

        {isSmooth === true && (
          <div className="animate-fade-in p-3 bg-emerald-50 rounded-xl border border-emerald-200">
            <p className="text-sm text-emerald-700">
              保存后系统将自动沉淀一条顺利沟通经验到您的个人话术库
            </p>
          </div>
        )}

        <div>
          <label className="text-sm font-medium text-gray-700 mb-3 block">
            补充个人话术（选填）
          </label>
          <div className="flex gap-2 mb-2 flex-wrap">
            {categoryOptions.map((cat) => (
              <button
                key={cat.value}
                onClick={() => setSelectedCategory(cat.value)}
                className={`px-3 py-1 text-xs rounded-md transition-colors ${
                  selectedCategory === cat.value
                    ? 'bg-blue-500 text-white'
                    : 'bg-gray-100 text-gray-500 hover:bg-gray-200'
                }`}
              >
                {cat.label}
              </button>
            ))}
          </div>
          <textarea
            value={speechContent}
            onChange={(e) => setSpeechContent(e.target.value)}
            placeholder="把今天用得好的话术记录下来，沉淀为个人常用话术..."
            rows={3}
            className="w-full px-4 py-3 text-sm border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 resize-none"
          />
        </div>

        <button
          onClick={handleSave}
          disabled={saved || isSmooth === null}
          className={`w-full py-3 rounded-xl font-medium transition-all duration-200 flex items-center justify-center gap-2 ${
            saved
              ? 'bg-emerald-500 text-white'
              : isSmooth === null
              ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
              : 'bg-blue-500 text-white hover:bg-blue-600 active:scale-[0.98]'
          }`}
        >
          {saved ? (
            <>
              <Check className="w-5 h-5" />
              保存成功
            </>
          ) : (
            <>
              <Save className="w-5 h-5" />
              保存复盘
            </>
          )}
        </button>
      </div>

      <div className="mt-4 bg-amber-50 rounded-xl p-3 flex items-start gap-2">
        <AlertCircle className="w-4 h-4 text-amber-500 flex-shrink-0 mt-0.5" />
        <p className="text-xs text-amber-700">
          保存后系统会根据沟通情况自动沉淀话术到个人库，您可以在话术库中编辑修改为自己的说法
        </p>
      </div>
    </div>
  );
}
