
import { useState } from 'react';
import { Bookmark, Trash2, Copy, Check, Tag, Search, Pencil, X, Save } from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';

const categoryLabels: Record<string, string> = {
  greeting: '开场问候',
  medical_history: '病史追问',
  pre_exam: '检查前说明',
  treatment_explain: '方案解释',
  closing: '结束语',
  objection_handling: '异议处理',
};

const allCategories = Object.entries(categoryLabels);

export function SpeechLibrary() {
  const personalSpeeches = useAppStore((state) => state.personalSpeeches);
  const deletePersonalSpeech = useAppStore((state) => state.deletePersonalSpeech);
  const updatePersonalSpeech = useAppStore((state) => state.updatePersonalSpeech);

  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [filterCategory, setFilterCategory] = useState<string | null>(null);
  const [searchKeyword, setSearchKeyword] = useState('');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editContent, setEditContent] = useState('');
  const [editCategory, setEditCategory] = useState('');

  const categories = [...new Set(personalSpeeches.map((s) => s.category))];

  const filteredSpeeches = personalSpeeches
    .filter((s) => !filterCategory || s.category === filterCategory)
    .filter((s) => {
      if (!searchKeyword.trim()) return true;
      const kw = searchKeyword.toLowerCase();
      return (
        s.content.toLowerCase().includes(kw) ||
        s.tags.some((t) => t.toLowerCase().includes(kw)) ||
        (categoryLabels[s.category] || '').includes(kw)
      );
    })
    .sort((a, b) => b.createdAt - a.createdAt);

  const handleCopy = async (content: string, id: string) => {
    try {
      await navigator.clipboard.writeText(content);
      setCopiedId(id);
      setTimeout(() => setCopiedId(null), 1500);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const startEdit = (id: string, content: string, category: string) => {
    setEditingId(id);
    setEditContent(content);
    setEditCategory(category);
  };

  const cancelEdit = () => {
    setEditingId(null);
    setEditContent('');
    setEditCategory('');
  };

  const saveEdit = () => {
    if (editingId && editContent.trim()) {
      updatePersonalSpeech(editingId, {
        content: editContent.trim(),
        category: editCategory,
      });
      setEditingId(null);
      setEditContent('');
      setEditCategory('');
    }
  };

  const formatDate = (timestamp: number) => {
    const date = new Date(timestamp);
    return `${date.getMonth() + 1}月${date.getDate()}日`;
  };

  const isAutoGenerated = (tags: string[]) => tags.includes('自动沉淀');

  return (
    <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-base font-semibold text-gray-800 flex items-center gap-2">
          <span className="w-1 h-5 bg-blue-500 rounded-full"></span>
          个人话术库
        </h3>
        <span className="text-xs text-gray-400">{personalSpeeches.length} 条</span>
      </div>

      <div className="space-y-3 mb-4">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input
            type="text"
            value={searchKeyword}
            onChange={(e) => setSearchKeyword(e.target.value)}
            placeholder="搜索话术内容、标签..."
            className="w-full pl-9 pr-4 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
          />
          {searchKeyword && (
            <button
              onClick={() => setSearchKeyword('')}
              className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>

        <div className="flex gap-2 flex-wrap">
          <button
            onClick={() => setFilterCategory(null)}
            className={`px-3 py-1 text-xs rounded-md transition-colors ${
              filterCategory === null
                ? 'bg-blue-500 text-white'
                : 'bg-gray-100 text-gray-500 hover:bg-gray-200'
            }`}
          >
            全部
          </button>
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setFilterCategory(cat)}
              className={`px-3 py-1 text-xs rounded-md transition-colors ${
                filterCategory === cat
                  ? 'bg-blue-500 text-white'
                  : 'bg-gray-100 text-gray-500 hover:bg-gray-200'
              }`}
            >
              {categoryLabels[cat] || cat}
            </button>
          ))}
        </div>
      </div>

      {filteredSpeeches.length > 0 ? (
        <div className="space-y-2 max-h-[500px] overflow-y-auto pr-1">
          {filteredSpeeches.map((speech) => (
            <div
              key={speech.id}
              className={`group p-3 rounded-xl border transition-all duration-200 ${
                editingId === speech.id
                  ? 'bg-blue-50 border-blue-300'
                  : 'bg-gray-50 hover:bg-blue-50 hover:border-blue-200 border-transparent'
              }`}
            >
              {editingId === speech.id ? (
                <div className="space-y-2">
                  <textarea
                    value={editContent}
                    onChange={(e) => setEditContent(e.target.value)}
                    rows={3}
                    className="w-full px-3 py-2 text-sm border border-blue-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/20 resize-none bg-white"
                  />
                  <div className="flex gap-2 flex-wrap">
                    {allCategories.map(([value, label]) => (
                      <button
                        key={value}
                        onClick={() => setEditCategory(value)}
                        className={`px-2 py-0.5 text-xs rounded-md transition-colors ${
                          editCategory === value
                            ? 'bg-blue-500 text-white'
                            : 'bg-gray-100 text-gray-500'
                        }`}
                      >
                        {label}
                      </button>
                    ))}
                  </div>
                  <div className="flex gap-2 justify-end">
                    <button
                      onClick={cancelEdit}
                      className="px-3 py-1.5 text-xs text-gray-500 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors"
                    >
                      取消
                    </button>
                    <button
                      onClick={saveEdit}
                      className="px-3 py-1.5 text-xs text-white bg-blue-500 rounded-lg hover:bg-blue-600 transition-colors flex items-center gap-1"
                    >
                      <Save className="w-3 h-3" />
                      保存
                    </button>
                  </div>
                </div>
              ) : (
                <>
                  <div className="flex items-start justify-between gap-2">
                    <p className="text-sm text-gray-700 flex-1 leading-relaxed">{speech.content}</p>
                    <div className="flex items-center gap-1 flex-shrink-0">
                      {copiedId === speech.id ? (
                        <span className="text-xs text-emerald-600 flex items-center gap-1">
                          <Check className="w-3 h-3" />
                          已复制
                        </span>
                      ) : (
                        <button
                          onClick={() => handleCopy(speech.content, speech.id)}
                          className="p-1.5 text-gray-400 hover:text-blue-500 hover:bg-blue-100 rounded-lg opacity-0 group-hover:opacity-100 transition-all"
                        >
                          <Copy className="w-4 h-4" />
                        </button>
                      )}
                      <button
                        onClick={() => startEdit(speech.id, speech.content, speech.category)}
                        className="p-1.5 text-gray-400 hover:text-amber-500 hover:bg-amber-100 rounded-lg opacity-0 group-hover:opacity-100 transition-all"
                      >
                        <Pencil className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => deletePersonalSpeech(speech.id)}
                        className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-100 rounded-lg opacity-0 group-hover:opacity-100 transition-all"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 mt-2">
                    <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-white text-xs text-gray-500 rounded-md">
                      <Tag className="w-3 h-3" />
                      {categoryLabels[speech.category] || speech.category}
                    </span>
                    {isAutoGenerated(speech.tags) && (
                      <span className="inline-flex items-center px-2 py-0.5 bg-amber-100 text-xs text-amber-600 rounded-md">
                        自动沉淀
                      </span>
                    )}
                    {speech.tags
                      .filter((t) => t && t !== speech.category && t !== '自动沉淀' && t !== '手动沉淀')
                      .slice(0, 2)
                      .map((tag) => (
                        <span
                          key={tag}
                          className="px-2 py-0.5 bg-gray-100 text-xs text-gray-500 rounded-md"
                        >
                          {tag}
                        </span>
                      ))}
                    <span className="text-xs text-gray-400 ml-auto">{formatDate(speech.createdAt)}</span>
                  </div>
                </>
              )}
            </div>
          ))}
        </div>
      ) : (
        <div className="text-center py-8">
          <div className="w-12 h-12 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-3">
            <Bookmark className="w-6 h-6 text-gray-400" />
          </div>
          <p className="text-sm text-gray-500 mb-1">
            {searchKeyword ? '没有找到匹配的话术' : '暂无个人话术'}
          </p>
          <p className="text-xs text-gray-400">
            {searchKeyword ? '试试换个关键词搜索' : '在接诊沟通中收藏或在复盘中沉淀'}
          </p>
        </div>
      )}
    </div>
  );
}
